version: "3.9"

services:
  simple-proxy:
    build:
      context: /tmp/empty
      dockerfile: ./Dockerfile.pk-proxy-image   # change if you named it differently
    container_name: pk-proxy-image
    ports:
      - "3000:3222"
    restart: unless-stopped
