version: "3.9"

services:
  simple-proxy:
    build:
      context: /tmp/empty
      dockerfile: pl-client-proxy.dockerfile   # change if you named it differently
    container_name: simple-proxy
    ports:
      - "3000:3222"
    restart: unless-stopped
