version: "3.9"

services:
  simple-proxy:
    build:
      context: /temp/empty
      dockerfile: Dockerfile   # change if you named it differently
    container_name: simple-proxy
    ports:
      - "3000:3222"
    restart: unless-stopped
