server_url: "https://alaska-headscale.ddnsgeek.com"
listen_addr: "0.0.0.0:8080"

# database
db_type: postgres
db_host: postgres.local
db_port: 5432
db_user: headscale
db_pass: secret
db_name: headscale


# enable DERP/STUN (helps with NAT traversal)
derp:
  urls:
    - https://controlplane.tailscale.com/derpmap/default
