FROM python:latest

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential gcc gfortran

RUN pip install --upgrade pip setuptools wheel

RUN pip install jupyterlab jupyter-collaboration

VOLUME ["/app"]

CMD ["jupyter","lab",
    "--allow-root",
    "--no-browser",
    "--collaborative",
    "--ip=0.0.0.0",
    "--port=1223",
    "--NotebookApp.token=''",
    "--NotebookApp.password=''"
    ]