version: "3.9"

services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - '5500:8080'
    volumes:
      - ./volumes/StirlingPDF/trainingData:/usr/share/ # Required for extra OCR languages
      - ./volumes/StirlingPDF/extraConfigs:/configs
      - ./volumes/StirlingPDF/customFiles:/customFiles/
      - ./volumes/StirlingPDF/logs:/logs/
      - ./volumes/StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
    restart: unless-stopped