version: "3.9"

services:

  jupyter-notebook:
    build:
      dockerfile: ./dockerimage/Dockerfile.jupyter-notebook
    ports:
      - '1223:1223'
    volumes:
      - ./volumes/jupyter:/app
    restart: unless-stopped
